<?php namespace BO4E\Enum;

/** DO NOT CHANGE THIS FILE - GENERATOR WILL OVERWRITE THIS FILE */

/** BDEW Artikelnummern */

enum BDEWArtikelnummer {

	case LEISTUNG;
	case LEISTUNG_PAUSCHAL;
	case GRUNDPREIS;
	case REGELENERGIE_ARBEIT;
	case REGELENERGIE_LEISTUNG;
	case NOTSTROMLIEFERUNG_ARBEIT;
	case NOTSTROMLIEFERUNG_LEISTUNG;
	case RESERVENETZKAPAZITAET;
	case RESERVELEISTUNG;
	case ZUSAETZLICHE_ABLESUNG;
	case PRUEFGEBUEHREN_AUSSERPLANMAESSIG;
	case WIRKARBEIT;
	case SINGULAER_GENUTZTE_BETRIEBSMITTEL;
	case ABGABE_KWKG;
	case ABSCHLAG;
	case KONZESSIONSABGABE;
	case ENTGELT_FERNAUSLESUNG;
	case UNTERMESSUNG;
	case BLINDMEHRARBEIT;
	case ENTGELT_ABRECHNUNG;
	case SPERRKOSTEN;
	case ENTSPERRKOSTEN;
	case MAHNKOSTEN;
	case MEHR_MINDERMENGEN;
	case INKASSOKOSTEN;
	case BLINDMEHRLEISTUNG;
	case ENTGELT_MESSUNG_ABLESUNG;
	case ENTGELT_EINBAU_BETRIEB_WARTUNG_MESSTECHNIK;
	case AUSGLEICHSENERGIE;
	case ZAEHLEINRICHTUNG;
	case WANDLER_MENGENUMWERTER;
	case KOMMUNIKATIONSEINRICHTUNG;
	case TECHNISCHE_STEUEREINRICHTUNG;
	case PARAGRAF_19_STROM_NEV_UMLAGE;
	case BEFESTIGUNGSEINRICHTUNG;
	case OFFSHORE_HAFTUNGSUMLAGE;
	case FIXE_ARBEITSENTGELTKOMPONENTE;
	case FIXE_LEISTUNGSENTGELTKOMPONENTE;
	case UMLAGE_ABSCHALTBARE_LASTEN;
	case MEHRMENGE;
	case MINDERMENGE;
	case ENERGIESTEUER;
	case SMARTMETER_GATEWAY;
	case STEUERBOX;
	case MSB_INKL_MESSUNG;
	case AUSGLEICHSENERGIE_UNTERDECKUNG;

}
