<?php namespace BO4E\Enum;

/** DO NOT CHANGE THIS FILE - GENERATOR WILL OVERWRITE THIS FILE */

/** List of possible Gebiettypen. */

enum Gebiettyp {

	case REGELZONE;
	case MARKTGEBIET;
	case BILANZIERUNGSGEBIET;
	case VERTEILNETZ;
	case TRANSPORTNETZ;
	case REGIONALNETZ;
	case AREALNETZ;
	case GRUNDVERSORGUNGSGEBIET;
	case VERSORGUNGSGEBIET;

}
