<?php namespace BO4E\Enum;

/** Auflistung möglicher abzurechnender Gerätetypen. */

enum Geraetetyp {

	case MULTIPLEXANLAGE;
	case PAUSCHALANLAGE;
	case VERSTAERKERANLAGE;
	case SUMMATIONSGERAET;
	case IMPULSGEBER;
	case MENGENUMWERTER;
	case STROMWANDLER;
	case SPANNUNGSWANDLER;
	case KOMBIMESSWANDLER;
	case BLOCKSTROMWANDLER;
	case DATENLOGGER;
	case KOMMUNIKATIONSANSCHLUSS;
	case MODEM;
	case TELEKOMMUNIKATIONSEINRICHTUNG;
	case MODERNE_MESSEINRICHTUNG;
	case INTELLIGENTES_MESSYSTEM;
	case STEUEREINRICHTUNG;
	case TARIFSCHALTGERAET;
	case RUNDSTEUEREMPFAENGER;
	case OPTIONALE_ZUS_ZAEHLEINRICHTUNG;
	case MESSWANDLERSATZ_IMS_MME;
	case KOMBIMESSWANDLER_IMS_MME;
	case TARIFSCHALTGERAET_IMS_MME;
	case RUNDSTEUEREMPFAENGER_IMS_MME;
	case TEMPERATUR_KOMPENSATION;
	case HOECHSTBELASTUNGS_ANZEIGER;
	case SONSTIGES_GERAET;
	case EDL_21;
	case EDL_40_ZAEHLERAUFSATZ;
	case EDL_40;
	case TELEFONANSCHLUSS;
	case MODEM_GSM;
	case MODEM_GPRS;
	case MODEM_FUNK;
	case MODEM_GSM_O_LG;
	case MODEM_GSM_M_LG;
	case MODEM_FESTNETZ;
	case MODEM_GPRS_M_LG;
	case PLC_KOM;
	case ETHERNET_KOM;
	case DSL_KOM;
	case LTE_KOM;
	case KOMPAKT_MU;
	case SYSTEM_MU;
	case TEMPERATUR_MU;
	case ZUSTANDS_MU;

}
