<?php namespace BO4E\Enum;

/** Auflistung der verschiedenen Berechnungsmethoden für ein Preisblatt. */

enum Kalkulationsmethode {

	case STUFEN;
	case ZONEN;
	case VORZONEN_GP;
	case SIGMOID;
	case BLINDARBEIT_GT_50_PROZENT;
	case BLINDARBEIT_GT_40_PROZENT;
	case BLINDARBEIT_MIT_FREIMENGE;
	case AP_GP_ZONEN;
	case LP_INSTALL_LEISTUNG;
	case AP_TRANSPORT_ODER_VERTEILNETZ;
	case AP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNETZ_SIGMOID;
	case LP_JAHRESVERBRAUCH;
	case LP_TRANSPORT_ODER_VERTEILNETZ;
	case LP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNETZ_SIGMOID;
	case FUNKTIONEN;
	case VERBRAUCH_UEBER_SLP_GRENZE_FUNKTIONSBEZOGEN_WEITERE_BERECHNUNG_ALS_LGK;

}
