<?php namespace BO4E\Enum;

/** DO NOT CHANGE THIS FILE - GENERATOR WILL OVERWRITE THIS FILE */

/**  */

enum Leistungstyp {

	case ARBEITSPREIS_WIRKARBEIT;
	case LEISTUNGSPREIS_WIRKLEISTUNG;
	case ARBEITSPREIS_BLINDARBEIT_IND;
	case ARBEITSPREIS_BLINDARBEIT_KAP;
	case GRUNDPREIS;
	case GRUNDPREIS_ARBEIT;
	case GRUNDPREIS_LEISTUNG;
	case MEHRMINDERMENGE;
	case MESSSTELLENBETRIEB;
	case MESSDIENSTLEISTUNG;
	case MESSDIENSTLEISTUNG_INKL_MESSUNG;
	case ABRECHNUNG;
	case KONZESSIONS_ABGABE;
	case KWK_UMLAGE;
	case OFFSHORE_UMLAGE;
	case ABLAV_UMLAGE;
	case SONDERKUNDEN_UMLAGE;
	case REGELENERGIE_UMLAGE;
	case BILANZIERUNG_UMLAGE;
	case AUSLESUNG_ZUSAETZLICH;
	case ABLESUNG_ZUSAETZLICH;
	case ABRECHNUNG_ZUSAETZLICH;
	case SPERRUNG;
	case ENTSPERRUNG;
	case MAHNKOSTEN;
	case INKASSOKOSTEN;
	case EEG_UMLAGE;
	case ENERGIESTEUER;
	case NETZPREIS;
	case MESSPREIS;
	case SONSTIGER_PREIS;
	case DIENSTLEISTUNG;

}
