<?php namespace BO4E\Enum;

/** DO NOT CHANGE THIS FILE - GENERATOR WILL OVERWRITE THIS FILE */

/** Festlegung, welcher Typ von Messung mit einem Preis belegt wird */

enum Messpreistyp {

	case MESSPREIS_G2_5;
	case MESSPREIS_G4;
	case MESSPREIS_G6;
	case MESSPREIS_G10;
	case MESSPREIS_G16;
	case MESSPREIS_G25;
	case MESSPREIS_G40;
	case ELEKTRONISCHER_AUFSATZ;
	case SMART_METER_MESSPREIS_G2_5;
	case SMART_METER_MESSPREIS_G4;
	case SMART_METER_MESSPREIS_G6;
	case SMART_METER_MESSPREIS_G10;
	case SMART_METER_MESSPREIS_G16;
	case SMART_METER_MESSPREIS_G25;
	case SMART_METER_MESSPREIS_G40;
	case VERRECHNUNGSPREIS_ET_WECHSEL;
	case VERRECHNUNGSPREIS_ET_DREH;
	case VERRECHNUNGSPREIS_ZT_WECHSEL;
	case VERRECHNUNGSPREIS_ZT_DREH;
	case VERRECHNUNGSPREIS_L_ET;
	case VERRECHNUNGSPREIS_L_ZT;
	case VERRECHNUNGSPREIS_SM;
	case AUFSCHLAG_WANDLER;
	case AUFSCHLAG_TARIFSCHALTUNG;

}
