<?php namespace BO4E\Enum;

/** DO NOT CHANGE THIS FILE - GENERATOR WILL OVERWRITE THIS FILE */

/** Klassifizierung der Kriterien für eine regionale Eingrenzung. */

enum Regionskriteriumtyp {

	case BUNDESLANDKENNZIFFER;
	case BUNDESLAND_NAME;
	case MARKTGEBIET_NUMMER;
	case MARKTGEBIET_NAME;
	case REGELGEBIET_NUMMER;
	case REGELGEBIET_NAME;
	case NETZ_STROM;
	case NETZ_GAS;
	case NETZBETREIBER_NUMMER_STROM;
	case NETZBETREIBER_NUMMER_GAS;
	case NETZBETREIBER_NAME_STROM;
	case NETZBETREIBER_NAME_GAS;
	case BILANZIERUNGS_GEBIET_NUMMER;
	case MSB_NUMMER;
	case MSB_NAME;
	case VERSORGER_NUMMER;
	case VERSORGER_NAME;
	case GRUNDVERSORGER_NUMMER_STROM;
	case GRUNDVERSORGER_NAME_STROM;
	case GRUNDVERSORGER_NUMMER_GAS;
	case GRUNDVERSORGER_NAME_GAS;
	case KREIS_NAME;
	case KREISKENNZIFFER;
	case GEMEINDE_NAME;
	case GEMEINDEKENNZIFFER;
	case POSTLEITZAHL;
	case ORT;
	case POSTORT;
	case EINWOHNERZAHL_GEMEINDE;
	case EINWOHNERZAHL_ORT;
	case KM_UMKREIS;
	case BUNDESWEIT;
	case PLZ_BEREICH;

}
