<?php namespace BO4E\Enum;

/** Über dieses ENUM kann eine thematische Zuordnung, beispielsweise eines Ansprechpartners, vorgenommen werden. */

enum Themengebiet {

	case ALLGEMEINER_INFORMATIONSAUSTAUSCH;
	case AN_UND_ABMELDUNG;
	case ANSPRECHPARTNER_ALLGEMEIN;
	case ANSPRECHPARTNER_BDEW_DVGW;
	case ANSPRECHPARTNER_IT_TECHNIK;
	case BILANZIERUNG;
	case BILANZKREISKOORDINATOR;
	case BILANZKREISVERANTWORTLICHER;
	case DATENFORMATE_ZERTIFIKATE_VERSCHLUESSELUNGEN;
	case DEBITORENMANAGEMENT;
	case DEMAND_SIDE_MANAGEMENT;
	case EDI_VEREINBARUNG;
	case EDIFACT;
	case ENERGIEDATENMANAGEMENT;
	case FAHRPLANMANAGEMENT;
	case ALOCAT;
	case APERAK;
	case CONTRL;
	case INVOIC;
	case MSCONS;
	case ORDERS;
	case ORDERSP;
	case REMADV;
	case UTILMD;
	case GABI;
	case GELI;
	case GERAETERUECKGABE;
	case GERAETEWECHSEL;
	case GPKE;
	case INBETRIEBNAHME;
	case KAPAZITAETSMANAGEMENT;
	case KLAERFAELLE;
	case LASTGAENGE_RLM;
	case LIEFERANTENRAHMENVERTRAG;
	case LIEFERANTENWECHSEL;
	case MABIS;
	case MAHNWESEN;
	case MARKTGEBIETSVERANTWORTLICHER;
	case MARKTKOMMUNIKATION;
	case MEHR_MINDERMENGEN;
	case MSB_MDL;
	case NETZABRECHNUNG;
	case NETZENTGELTE;
	case NETZMANAGEMENT;
	case RECHT;
	case REGULIERUNGSMANAGEMENT;
	case REKLAMATIONEN;
	case SPERREN_ENTSPERREN_INKASSO;
	case STAMMDATEN;
	case STOERUNGSFAELLE;
	case TECHNISCHE_FRAGEN;
	case UMSTELLUNG_INVOIC;
	case VERSCHLUESSELUNG_SIGNATUR;
	case VERTRAGSMANAGEMENT;
	case VERTRIEB;
	case WIM;
	case ZAEHLERSTAENDE_SLP;
	case ZAHLUNGSVERKEHR;
	case ZUORDNUNGSVEREINBARUNG;

}
