<?php namespace BO4E\Enum;

/** Auflistung sämtlicher existierender Geschäftsobjekte. */

enum Typ {

	case ANGEBOT;
	case ANSPRECHPARTNER;
	case AUSSCHREIUNG;
	case BUENDELVERTRAG;
	case ENERGIEMENGE;
	case FREMDKOSTEN;
	case GERAET;
	case GESCHAEFTSOBJEKT;
	case GESCHAEFTSPARTNER;
	case KOSTEN;
	case LASTGANG;
	case LASTGANG_KOMPAKT;
	case MARKTLOKATION;
	case MESSLOKATION;
	case MARKTTEILNEHMER;
	case NETZNUTZUNGSRECHNUNG;
	case PREISBLATT;
	case PREISBLATTDIENSTLEISTUNG;
	case PREISBLATTHARDWARE;
	case PREISBLATTKONZESSIONSABGABE;
	case PREISBLATTMESSUNG;
	case PREISBLATTNETZNUTZUNG;
	case PREISBLATTUMLAGEN;
	case RECHNUNG;
	case REGION;
	case REGIONALTARIF;
	case STANDORTEIGENSCHAFTEN;
	case TARIF;
	case TARIFINFO;
	case TARIFKOSTEN;
	case TARIFPREISBLATT;
	case VERTRAG;
	case ZAEHLER;
	case ZEITREIHE;

}
