<?php namespace BO4E\Enum;

/** DO NOT CHANGE THIS FILE - GENERATOR WILL OVERWRITE THIS FILE */

/** Aufzählung der Vertragsarten. */

enum Vertragsart {

	case ENERGIELIEFERVERTRAG;
	case NETZNUTZUNGSVERTRAG;
	case BILANZIERUNGSVERTRAG;
	case MESSSTELLENBETRIEBSVERTRAG;
	case BUENDELVERTRAG;

}
