<?php namespace BO4E\Enum;

/** DO NOT CHANGE THIS FILE - GENERATOR WILL OVERWRITE THIS FILE */

/** Verwendungszweck der Werte Marktlokation */

enum Verwendungszweck {

	case NETZNUTZUNGSABRECHNUNG;
	case BILANZKREISABRECHNUNG;
	case MEHRMINDERMENGENABRECHNUNG;
	case ENDKUNDENABRECHNUNG;
	case UEBERMITTLUNG_AN_DAS_HKNR;
	case ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS;

}
