<?php namespace BO4E\Enum;

/** DO NOT CHANGE THIS FILE - GENERATOR WILL OVERWRITE THIS FILE */

/** Voraussetzungen, die erfüllt sein müssen, damit dieser Tarif zur Anwendung kommen kann. */

enum Voraussetzungen {

	case EINZUGSERMAECHTIGUNG;
	case ZEITPUNKT;
	case LIEFERANBINDUNG_EINE;
	case LIEFERANBINDUNG_ALLE;
	case GEWERBE;
	case LASTPROFIL;
	case ZAEHLERTYP_GROESSE;
	case AUSSCHLUSS_GROSSVERBRAUCHER;
	case NEUKUNDE;
	case BESTIMMTE_VERTRAGSFORMALITAETEN;
	case SELBSTABLESUNG;
	case ONLINEVORAUSSETZUNG;
	case MINDESTUMSATZ;
	case ZUSATZPRODUKT;
	case NEUKUNDE_MIT_VORAUSSETZUNGEN;
	case DIREKTVERTRIEB;
	case ANSCHLUSSART;
	case ANSCHLUSSWERT;
	case ALTER_KUNDENANLAGE;
	case ANLAGEBESCHAFFENHEIT;
	case BETRIEBSSTUNDENBEGRENZUNG;
	case FREIGABEZEITEN;
	case FAMILIENSTRUKTUR;
	case MITGLIEDSCHAFT;
	case STAATLICHE_FOERDERUNG;
	case BESONDERE_VERBRAUCHSSTELLE;
	case NIEDRIGENERGIE;
	case ORTSTEILE_LIEFERGEBIET;
	case WAERMEBEDARF_ERDGAS;
	case MAX_ZAEHLER_LIEFERSTELLEN;
	case LIEFERUNGSBESCHRAENKUNG_GASART;
	case KOMBI_BONI;
	case ALTVERTRAG;
	case VORGESCHRIEBENE_ZUSATZANLAGE;
	case MEHRERE_ZAEHLER_ABNAHMESTELLEN;
	case BESTIMMTER_ABNAHMEFALL;
	case ZUSATZMODALITAET;
	case NACHWEIS_ZAHLUNGSFAEHIGKEIT;
	case UMSTELLUNG_ENERGIEART;

}
